export const AuthActionTypes = {
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
};

export const CardsActionTypes = {
  CREATE_CARD: 'CREATE_CARD',
  DELETE_CARD: 'DELETE_CARD',
  FETCH_CARDS_START: 'FETCH_CARDS_START',
  FETCH_CARDS_SUCCESS: 'FETCH_CARDS_SUCCESS',
  FETCH_CARDS_ERROR: 'FETCH_CARDS_ERROR',
};
